<?php $helper = Mage::helper('bpost_shm') ?>
<p><?php echo $helper->__('Bpost Shipping Manager is a service offered by Bpost,
 Allowing your customer to chose their preferred delivery method when ordering in your webshop.') ?></p>
<p><?php echo $helper->__('The following delivery methods are currently supported:') ?></p>
<ul>
    <li><?php echo $helper->__('Receive your parcel at home or at the office.') ?></li>
    <li><?php echo $helper->__('Over 1.250 locations nearby home or the office.') ?></li>
    <li><?php echo $helper->__('Pick-up your parcel whenever you want, thanks to the 24/7 service of bpost.') ?></li>
</ul>
<p><?php echo $helper->__('When activated and correctly installed,
this module also allows you to completely integrate the bpost administration into your webshop.') ?></p>
<p><?php echo $helper->__('This means that orders are automatically added to the bpost portal.') ?></p>
<p><?php echo $helper->__('Furthermore, if enabled, it is possible to generate your labels and trakcing codes directly from the Magento order admin page.') ?></p>
<p><?php echo $helper->__('No more hassle and 100% transparent!') ?></p>
<p><?php echo $helper->__('<a target="_blank" href="%s">Documentation</a>: links to the bpost freshdesk for Magento',"http://bpost.freshdesk.com/solution/categories/99521/folders/4000013305");?></p>